services:
  openldap:
    image: bitnami/openldap:2.6.6
    container_name: openldap
    restart: unless-stopped
    volumes:
      - ./ldifs:/docker-entrypoint-initdb.d
      - ../certs/openldap.crt:/opt/bitnami/openldap/certs/openldap.crt
      - ../certs/openldap.key:/opt/bitnami/openldap/certs/openldap.key
      - ../certs/openldapCA.crt:/opt/bitnami/openldap/certs/openldapCA.crt
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpass
      - LDAP_ROOT=dc=snef,dc=fr
      - LDAP_CUSTOM_LDIF_DIR=/docker-entrypoint-initdb.d

      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt
      - LDAP_REQUIRE_TLS=yes
      - LDAP_TLS_VERIFY_CLIENT=never # Pour dev uniquement
    ports:
      - "1389:1389"