services:
  openldap:
    image: bitnami/openldap:2.6.6
    container_name: openldap
    restart: unless-stopped
    volumes:
      - ./ldifs:/docker-entrypoint-initdb.d
      - ./certs:/opt/bitnami/openldap/certs
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpass
      - LDAP_ROOT=dc=snef,dc=fr
      - LDAP_CUSTOM_LDIF_DIR=/docker-entrypoint-initdb.d
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt
    ports:
      - "1389:1389"
    
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap://openldap:1389
      PHPLDAPADMIN_HTTPS: false
      PHPLDAPADMIN_LDAP_CLIENT_TLS: 0
    ports:
      - "80:80"
    depends_on:
      - openldap